services:
  db:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: enggal_group
    ports:
      - 5435:5432
    networks:
      - app_network
    restart: unless-stopped
    healthcheck:
      test: [ CMD-SHELL, pg_isready -d enggal_group -U postgres ]

      interval: 5s
      timeout: 5s
      retries: 5

networks:
  app_network:
    external: true
