/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserCareerRouteImport } from './routes/user-career'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as BrandRouteImport } from './routes/brand'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PromoIndexRouteImport } from './routes/promo/index'
import { Route as OutletIndexRouteImport } from './routes/outlet/index'
import { Route as BeritaIndexRouteImport } from './routes/berita/index'
import { Route as PromoCreateRouteImport } from './routes/promo/create'
import { Route as OutletCreateRouteImport } from './routes/outlet/create'
import { Route as BeritaCreateRouteImport } from './routes/berita/create'
import { Route as PromoPromoIdEditRouteImport } from './routes/promo/$promoId/edit'
import { Route as OutletOutletIdEditRouteImport } from './routes/outlet/$outletId/edit'
import { Route as BeritaBeritaIdEditRouteImport } from './routes/berita/$beritaId/edit'

const AboutLazyRouteImport = createFileRoute('/about')()

const AboutLazyRoute = AboutLazyRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))
const UserCareerRoute = UserCareerRouteImport.update({
  id: '/user-career',
  path: '/user-career',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PromoIndexRoute = PromoIndexRouteImport.update({
  id: '/promo/',
  path: '/promo/',
  getParentRoute: () => rootRouteImport,
} as any)
const OutletIndexRoute = OutletIndexRouteImport.update({
  id: '/outlet/',
  path: '/outlet/',
  getParentRoute: () => rootRouteImport,
} as any)
const BeritaIndexRoute = BeritaIndexRouteImport.update({
  id: '/berita/',
  path: '/berita/',
  getParentRoute: () => rootRouteImport,
} as any)
const PromoCreateRoute = PromoCreateRouteImport.update({
  id: '/promo/create',
  path: '/promo/create',
  getParentRoute: () => rootRouteImport,
} as any)
const OutletCreateRoute = OutletCreateRouteImport.update({
  id: '/outlet/create',
  path: '/outlet/create',
  getParentRoute: () => rootRouteImport,
} as any)
const BeritaCreateRoute = BeritaCreateRouteImport.update({
  id: '/berita/create',
  path: '/berita/create',
  getParentRoute: () => rootRouteImport,
} as any)
const PromoPromoIdEditRoute = PromoPromoIdEditRouteImport.update({
  id: '/promo/$promoId/edit',
  path: '/promo/$promoId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const OutletOutletIdEditRoute = OutletOutletIdEditRouteImport.update({
  id: '/outlet/$outletId/edit',
  path: '/outlet/$outletId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const BeritaBeritaIdEditRoute = BeritaBeritaIdEditRouteImport.update({
  id: '/berita/$beritaId/edit',
  path: '/berita/$beritaId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brand': typeof BrandRoute
  '/settings': typeof SettingsRoute
  '/user-career': typeof UserCareerRoute
  '/about': typeof AboutLazyRoute
  '/berita/create': typeof BeritaCreateRoute
  '/outlet/create': typeof OutletCreateRoute
  '/promo/create': typeof PromoCreateRoute
  '/berita': typeof BeritaIndexRoute
  '/outlet': typeof OutletIndexRoute
  '/promo': typeof PromoIndexRoute
  '/berita/$beritaId/edit': typeof BeritaBeritaIdEditRoute
  '/outlet/$outletId/edit': typeof OutletOutletIdEditRoute
  '/promo/$promoId/edit': typeof PromoPromoIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brand': typeof BrandRoute
  '/settings': typeof SettingsRoute
  '/user-career': typeof UserCareerRoute
  '/about': typeof AboutLazyRoute
  '/berita/create': typeof BeritaCreateRoute
  '/outlet/create': typeof OutletCreateRoute
  '/promo/create': typeof PromoCreateRoute
  '/berita': typeof BeritaIndexRoute
  '/outlet': typeof OutletIndexRoute
  '/promo': typeof PromoIndexRoute
  '/berita/$beritaId/edit': typeof BeritaBeritaIdEditRoute
  '/outlet/$outletId/edit': typeof OutletOutletIdEditRoute
  '/promo/$promoId/edit': typeof PromoPromoIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brand': typeof BrandRoute
  '/settings': typeof SettingsRoute
  '/user-career': typeof UserCareerRoute
  '/about': typeof AboutLazyRoute
  '/berita/create': typeof BeritaCreateRoute
  '/outlet/create': typeof OutletCreateRoute
  '/promo/create': typeof PromoCreateRoute
  '/berita/': typeof BeritaIndexRoute
  '/outlet/': typeof OutletIndexRoute
  '/promo/': typeof PromoIndexRoute
  '/berita/$beritaId/edit': typeof BeritaBeritaIdEditRoute
  '/outlet/$outletId/edit': typeof OutletOutletIdEditRoute
  '/promo/$promoId/edit': typeof PromoPromoIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brand'
    | '/settings'
    | '/user-career'
    | '/about'
    | '/berita/create'
    | '/outlet/create'
    | '/promo/create'
    | '/berita'
    | '/outlet'
    | '/promo'
    | '/berita/$beritaId/edit'
    | '/outlet/$outletId/edit'
    | '/promo/$promoId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brand'
    | '/settings'
    | '/user-career'
    | '/about'
    | '/berita/create'
    | '/outlet/create'
    | '/promo/create'
    | '/berita'
    | '/outlet'
    | '/promo'
    | '/berita/$beritaId/edit'
    | '/outlet/$outletId/edit'
    | '/promo/$promoId/edit'
  id:
    | '__root__'
    | '/'
    | '/brand'
    | '/settings'
    | '/user-career'
    | '/about'
    | '/berita/create'
    | '/outlet/create'
    | '/promo/create'
    | '/berita/'
    | '/outlet/'
    | '/promo/'
    | '/berita/$beritaId/edit'
    | '/outlet/$outletId/edit'
    | '/promo/$promoId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandRoute: typeof BrandRoute
  SettingsRoute: typeof SettingsRoute
  UserCareerRoute: typeof UserCareerRoute
  AboutLazyRoute: typeof AboutLazyRoute
  BeritaCreateRoute: typeof BeritaCreateRoute
  OutletCreateRoute: typeof OutletCreateRoute
  PromoCreateRoute: typeof PromoCreateRoute
  BeritaIndexRoute: typeof BeritaIndexRoute
  OutletIndexRoute: typeof OutletIndexRoute
  PromoIndexRoute: typeof PromoIndexRoute
  BeritaBeritaIdEditRoute: typeof BeritaBeritaIdEditRoute
  OutletOutletIdEditRoute: typeof OutletOutletIdEditRoute
  PromoPromoIdEditRoute: typeof PromoPromoIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-career': {
      id: '/user-career'
      path: '/user-career'
      fullPath: '/user-career'
      preLoaderRoute: typeof UserCareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promo/': {
      id: '/promo/'
      path: '/promo'
      fullPath: '/promo'
      preLoaderRoute: typeof PromoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outlet/': {
      id: '/outlet/'
      path: '/outlet'
      fullPath: '/outlet'
      preLoaderRoute: typeof OutletIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berita/': {
      id: '/berita/'
      path: '/berita'
      fullPath: '/berita'
      preLoaderRoute: typeof BeritaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promo/create': {
      id: '/promo/create'
      path: '/promo/create'
      fullPath: '/promo/create'
      preLoaderRoute: typeof PromoCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outlet/create': {
      id: '/outlet/create'
      path: '/outlet/create'
      fullPath: '/outlet/create'
      preLoaderRoute: typeof OutletCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berita/create': {
      id: '/berita/create'
      path: '/berita/create'
      fullPath: '/berita/create'
      preLoaderRoute: typeof BeritaCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promo/$promoId/edit': {
      id: '/promo/$promoId/edit'
      path: '/promo/$promoId/edit'
      fullPath: '/promo/$promoId/edit'
      preLoaderRoute: typeof PromoPromoIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outlet/$outletId/edit': {
      id: '/outlet/$outletId/edit'
      path: '/outlet/$outletId/edit'
      fullPath: '/outlet/$outletId/edit'
      preLoaderRoute: typeof OutletOutletIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berita/$beritaId/edit': {
      id: '/berita/$beritaId/edit'
      path: '/berita/$beritaId/edit'
      fullPath: '/berita/$beritaId/edit'
      preLoaderRoute: typeof BeritaBeritaIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrandRoute: BrandRoute,
  SettingsRoute: SettingsRoute,
  UserCareerRoute: UserCareerRoute,
  AboutLazyRoute: AboutLazyRoute,
  BeritaCreateRoute: BeritaCreateRoute,
  OutletCreateRoute: OutletCreateRoute,
  PromoCreateRoute: PromoCreateRoute,
  BeritaIndexRoute: BeritaIndexRoute,
  OutletIndexRoute: OutletIndexRoute,
  PromoIndexRoute: PromoIndexRoute,
  BeritaBeritaIdEditRoute: BeritaBeritaIdEditRoute,
  OutletOutletIdEditRoute: OutletOutletIdEditRoute,
  PromoPromoIdEditRoute: PromoPromoIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
