/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserCareerRouteImport } from './routes/user-career'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OutletRouteImport } from './routes/outlet'
import { Route as BrandRouteImport } from './routes/brand'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PromoIndexRouteImport } from './routes/promo/index'
import { Route as BeritaIndexRouteImport } from './routes/berita/index'
import { Route as PromoCreateRouteImport } from './routes/promo/create'
import { Route as BeritaCreateRouteImport } from './routes/berita/create'

const AboutLazyRouteImport = createFileRoute('/about')()

const AboutLazyRoute = AboutLazyRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))
const UserCareerRoute = UserCareerRouteImport.update({
  id: '/user-career',
  path: '/user-career',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OutletRoute = OutletRouteImport.update({
  id: '/outlet',
  path: '/outlet',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PromoIndexRoute = PromoIndexRouteImport.update({
  id: '/promo/',
  path: '/promo/',
  getParentRoute: () => rootRouteImport,
} as any)
const BeritaIndexRoute = BeritaIndexRouteImport.update({
  id: '/berita/',
  path: '/berita/',
  getParentRoute: () => rootRouteImport,
} as any)
const PromoCreateRoute = PromoCreateRouteImport.update({
  id: '/promo/create',
  path: '/promo/create',
  getParentRoute: () => rootRouteImport,
} as any)
const BeritaCreateRoute = BeritaCreateRouteImport.update({
  id: '/berita/create',
  path: '/berita/create',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brand': typeof BrandRoute
  '/outlet': typeof OutletRoute
  '/settings': typeof SettingsRoute
  '/user-career': typeof UserCareerRoute
  '/about': typeof AboutLazyRoute
  '/berita/create': typeof BeritaCreateRoute
  '/promo/create': typeof PromoCreateRoute
  '/berita': typeof BeritaIndexRoute
  '/promo': typeof PromoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brand': typeof BrandRoute
  '/outlet': typeof OutletRoute
  '/settings': typeof SettingsRoute
  '/user-career': typeof UserCareerRoute
  '/about': typeof AboutLazyRoute
  '/berita/create': typeof BeritaCreateRoute
  '/promo/create': typeof PromoCreateRoute
  '/berita': typeof BeritaIndexRoute
  '/promo': typeof PromoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brand': typeof BrandRoute
  '/outlet': typeof OutletRoute
  '/settings': typeof SettingsRoute
  '/user-career': typeof UserCareerRoute
  '/about': typeof AboutLazyRoute
  '/berita/create': typeof BeritaCreateRoute
  '/promo/create': typeof PromoCreateRoute
  '/berita/': typeof BeritaIndexRoute
  '/promo/': typeof PromoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brand'
    | '/outlet'
    | '/settings'
    | '/user-career'
    | '/about'
    | '/berita/create'
    | '/promo/create'
    | '/berita'
    | '/promo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brand'
    | '/outlet'
    | '/settings'
    | '/user-career'
    | '/about'
    | '/berita/create'
    | '/promo/create'
    | '/berita'
    | '/promo'
  id:
    | '__root__'
    | '/'
    | '/brand'
    | '/outlet'
    | '/settings'
    | '/user-career'
    | '/about'
    | '/berita/create'
    | '/promo/create'
    | '/berita/'
    | '/promo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandRoute: typeof BrandRoute
  OutletRoute: typeof OutletRoute
  SettingsRoute: typeof SettingsRoute
  UserCareerRoute: typeof UserCareerRoute
  AboutLazyRoute: typeof AboutLazyRoute
  BeritaCreateRoute: typeof BeritaCreateRoute
  PromoCreateRoute: typeof PromoCreateRoute
  BeritaIndexRoute: typeof BeritaIndexRoute
  PromoIndexRoute: typeof PromoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-career': {
      id: '/user-career'
      path: '/user-career'
      fullPath: '/user-career'
      preLoaderRoute: typeof UserCareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outlet': {
      id: '/outlet'
      path: '/outlet'
      fullPath: '/outlet'
      preLoaderRoute: typeof OutletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promo/': {
      id: '/promo/'
      path: '/promo'
      fullPath: '/promo'
      preLoaderRoute: typeof PromoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berita/': {
      id: '/berita/'
      path: '/berita'
      fullPath: '/berita'
      preLoaderRoute: typeof BeritaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promo/create': {
      id: '/promo/create'
      path: '/promo/create'
      fullPath: '/promo/create'
      preLoaderRoute: typeof PromoCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berita/create': {
      id: '/berita/create'
      path: '/berita/create'
      fullPath: '/berita/create'
      preLoaderRoute: typeof BeritaCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrandRoute: BrandRoute,
  OutletRoute: OutletRoute,
  SettingsRoute: SettingsRoute,
  UserCareerRoute: UserCareerRoute,
  AboutLazyRoute: AboutLazyRoute,
  BeritaCreateRoute: BeritaCreateRoute,
  PromoCreateRoute: PromoCreateRoute,
  BeritaIndexRoute: BeritaIndexRoute,
  PromoIndexRoute: PromoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
